# =================================================================================================
# Project       : YUKI-MONGODB
# Official Repo : https://github.com/SUDEEPBOTS/YUKI-MONGODB
# Description   : Render PaaS Infrastructure-as-Code Blueprint
# Maintainer    : SUDEEPBOTS <https://github.com/SUDEEPBOTS>
#
# Copyright (c) 2026 SUDEEPBOTS. All rights reserved.
# Licensed under the MIT License (https://opensource.org/licenses/MIT)
# =================================================================================================

services:
  - type: web
    name: yuki-mongodb
    env: docker
    plan: free
    region: singapore
    dockerfilePath: Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_PORT
        value: 27017
      - key: CACHE_SIZE_GB
        value: 0.25
      - key: MONGO_USER
        sync: false
      - key: MONGO_PASS
        sync: false
      - key: DOMAIN
        value: mongo.yukiapi.site
      - key: SYNC_INTERVAL_MIN
        value: 5
      - key: SESSION_STRING
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: TUNNEL_TOKEN
        sync: false
